services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    authentication.handler.login_success_handler:
        class:  AdminBundle\Service\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']