# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../vendor/components/jquery/jquery.min.js'
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/js/bootstrap.min.js'
        bootstrap_css:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.css'
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap-theme.css'
        bootstrap_glyphicons_ttf:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf'
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot'
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg'
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: "fonts/glyphicons-halflings-regular.woff"
        bootstrap_glyphicons_woff2:
            inputs:
                - '%kernel.root_dir%/../vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2'
            output: "fonts/glyphicons-halflings-regular.woff2"