# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        admin:
            pattern:            /adm(.*)
            form_login:
                provider:       fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:     /adm/login
                check_path:     /%admin_route%/login_check
                success_handler: authentication.handler.login_success_handler
            logout:
                path:           /%admin_route%/logout
                target:         /%admin_route%/login
            anonymous: ~

        main:
            pattern:  ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                success_handler: authentication.handler.login_success_handler
            logout:
                path:   /logout
                target: /
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/%admin_route%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/request$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/send-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/check-email$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/reset/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/confirm, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_route%/, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }