services:
#    symshop.example:
#        class: SymshopBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    authentication.handler.login_success_handler:
        class:  SymshopBundle\Service\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']